### ISSUE TITLE
Revert using validation by default.

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [overblog/ThriftBundle#12]
There's a problem with the validation which I've just met.
If you have a neither optional nor required field like ```8: i32 level``` it is treated optional when reading structs but is treated as required on writing and generates an exception:
```
    if ($this->level === null) {
      throw new TProtocolException('Required field PlayerProfile.level is unset!');
    }
```
So practically you can receive such messages but can't send them. :angry:
More on this: http://lionet.info/asn1c/blog/2010/07/18/thrift-semantics/

So I suggest reverting 5e2827a4a4ba40cfc6bd8186a8c4210f77dd56a7 and ac0f20797d7da4902204652c949dbf43317315f4.

**Comment by xkobal** [comment]
Sad news.

I have cancelled the merge. 

Maybe it's a just something to correct une the apache/thrift library.

Thanks
