### ISSUE TITLE
Symfony 2.3 No Longer Supported?

### ISSUE THREAD

**Issue by bmeynell** [overblog/ThriftBundle#19]
Looks like a `>=2.4` constraint was added to the `symfony/symfony` package in a recent commit --> https://github.com/overblog/ThriftBundle/commit/8724ee5821001ea7fd2f30091791b30cde0ba462#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R16. Is there a specific reason for this or can we allow this to be installed on Symfony 2.3 installations as well?

If it helps, here's the output I got when trying to install this bundle on `2.3.42`:

Confim Version:

```
$ ./app/console --version
Symfony version 2.3.42 - app/dev/debug
```

Attempted Install:

```
$ php -d memory_limit=-1 /usr/local/bin/composer.phar require overblog/thrift-bundle --verbose --profile
[snip]
[1391.2MB/132.86s] Your requirements could not be resolved to an installable set of packages.
[1391.2MB/132.86s]
  Problem 1
    - Installation request for overblog/thrift-bundle ^0.10.0 -> satisfiable by overblog/thrift-bundle[v0.10].
    - overblog/thrift-bundle v0.10 requires symfony/symfony ~2.4|~3.0 -> satisfiable by symfony/symfony[2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev, 2.8.x-dev, 3.0.x-dev, 3.1.x-dev, 3.2.x-dev, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.0-BETA1, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.0-BETA1, v3.1.0-RC1, v3.1.1, v3.1.2, v3.1.3, v3.1.4] but these conflict with your requirements or minimum-stability.
```

**Comment by bmeynell** [comment]
Ping @AlexeyKupershtokh - Thoughts?

**Comment by mcg-web** [comment]
Hi @bmeynell we have move to minimum symfony 2.4 requirement, it there a reason you want to use 2.3?

**Comment by bmeynell** [comment]
Hi @mcg-web, we're running 2.3 currently, but will be upgrading to 2.8 "soon". Until then I'd love to use this bundle in 2.3. Is there functionality in the bundle that 2.3 does not support? If not, can we make the min requirement 2.3 until the bundle uses non-2.3 features?

**Comment by mcg-web** [comment]
The bundle are not tested for every single symfony version for the moment that's why i can't answer to this question. I'm a new come on the project, I'll put a travis test in place to insure that 2.3 are supported.

**Comment by bmeynell** [comment]
@mcg-web - FWIW I pinged @xkobal on Twitter late last week and he said there's nothing impeding this bundle from running on 2.3. Reference https://twitter.com/bmeynell/status/774214099785973760.

**Comment by mcg-web** [comment]
I do the test and the classloader component seem missing in sf 2.3, so i added it, but also failled for the moment... I'll try to push a fix in the day.

**Comment by mcg-web** [comment]
@bmeynell  can you confirm that it work for you `composer require "overblog/thrift-bundle:dev-sf_2_3"` please? it will be merge after adding travis to test symfony versions, I'll keep this branch up to date in the middle time...

**Comment by bmeynell** [comment]
@mcg-web - Confirmed. I was able to install and use the bundle on 2.3 with the instructions you provided.

**Comment by mcg-web** [comment]
@bmeynell thank you, I'm closing this issue now that branch is merged...
