### ISSUE TITLE
Bug when using Bundle inheritance

### ISSUE THREAD

**Issue by OwlyCode** [overblog/ThriftBundle#3]
Hello,

I created a bundle called RemoteUserBundle. Then I implemented in it an SSO authentication making use of Thrift as a user provider.

I now want to make this bundle generic, and create another bundle, let's call it MyAppUserBundle. This is the bundle where I override the user entity to add to it some fields and relations.

When I do this and refresh my page, it says that it can't find my Thrift definition into a folder under the new bundle. Why do thrift searches into this one? 

It was working perfectly when I only used RemoteUserBundle. It seems that OverblogThriftBundle is attempting to load the thrift definition files from the inheriting bundle of the one declared in the config.yml (bundleNameIn).

Copying the folder to the new bundle fixes the problem.

**Comment by xkobal** [comment]
Fixed because we remove definition loading with bundle name :D
