### ISSUE TITLE
Add custom headers to http client requests

### ISSUE THREAD

**Issue by lcordingley** [overblog/ThriftBundle#30]
Is there a way I could add custom HTTP headers for clients using http transport? 

If I understand the your bundle correctly, based on the thrift client config it injects instances of [`Overblog\ThriftBundle\Client\HttpClient`](https://github.com/overblog/ThriftBundle/blob/master/Client/HttpClient.php#L43) dynamically into the container. If you look at the returned `$socket` variable which is an instance of `Thrift\Transport\THttpClient` I would simply need to call method `addHeaders()` to add custom headers to the request. I have tried finding a way to have your bundle pick up my own class in my `AppBundle` that extends your class but the OverblogThrift bundle seems to pull its config directly from its own yml file `Resources/config/services.yml` and I have not been able to successfully provide overrides for any of the parameters. I have tried to [extend the `OverblogThriftBundle` bundle with no luck](http://symfony.com/doc/2.8/bundles/override.html). I have also tried to overwrite DI container parameters via a [Compiler Pass](http://symfony.com/doc/2.8/service_container/compiler_passes.html) but it seems that the compiler pass happens prior to `ThriftBundle/DependencyInjection/OverblogThriftExtension.php` which dynamically adds the client services into the container. Is there a way to overwrite or extend OverblogThriftBundle's `HttpClient` class to allow me to add custom headers to the instance of `Thrift\Transport\THttpClient`? I am running Symfony version 2.8. Any help regarding how to do this is greatly appreciated!

**Comment by ooflorent** [comment]
You could listen to `kernel.response` event modify response headers.

```php
public function onKernelResponse(FilterResponseEvent $event)
{
    $response = $event->getResponse();
    $response->headers->set('X-Custom', 'hello');
}
```

If you really need to control the `Server` instance, then I think the bundle does not allow it.
