### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by edmeister** [overblog/ThriftBundle#5]
I tried to include the Bundle in a fresh installation of Symfony 2.4 and got these errors when trying to update composer:

composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for overblog/thrift-bundle dev-master -> satisfiable by overblog/thrift-bundle[dev-master].
    - overblog/thrift-bundle dev-master requires ebuzzing/thrift 0.9.1.x-dev -> no matching package found.
  Problem 2
    - overblog/thrift-bundle dev-master requires ebuzzing/thrift 0.9.1.x-dev -> no matching package found.
    - symfony/framework-standard-edition 2.4.x-dev requires overblog/thrift-bundle dev-master -> satisfiable by overblog/thrift-bundle[dev-master].
    - Installation request for symfony/framework-standard-edition 2.4.x-dev -> satisfiable by symfony/framework-standard-edition[2.4.x-dev].

**Comment by xkobal** [comment]
Fixed, because we stop to fork apache/thrift.
